[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm --prefix app install']

[phases.build]
cmds = ['npm --prefix app run build', 'cp -r app/dist ./dist']

[start]
cmd = 'npx serve -s dist -l 3000'
